# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-23 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CommonCourse',
        ),
        migrations.RenameField(
            model_name='pricepolicy',
            old_name='table_name',
            new_name='content_type',
        ),
    ]
